alter table RICARDUINO_INGREDIENT add constraint FK_RICARDUINO_INGREDIENT_ON_PICTURE foreign key (PICTURE_ID) references SYS_FILE(ID);
alter table RICARDUINO_INGREDIENT add constraint FK_RICARDUINO_INGREDIENT_ON_ACTUATOR foreign key (ACTUATOR_ID) references RICARDUINO_ACTUATOR(ID);
create unique index IDX_RICARDUINO_INGREDIENT_UK_NAME on RICARDUINO_INGREDIENT (NAME) where DELETE_TS is null ;
create index IDX_RICARDUINO_INGREDIENT_ON_PICTURE on RICARDUINO_INGREDIENT (PICTURE_ID);
create index IDX_RICARDUINO_INGREDIENT_ON_ACTUATOR on RICARDUINO_INGREDIENT (ACTUATOR_ID);
