alter table RICARDUINO_GLASS add constraint FK_RICARDUINO_GLASS_ON_PICTURE foreign key (PICTURE_ID) references SYS_FILE(ID);
create unique index IDX_RICARDUINO_GLASS_UK_NAME on RICARDUINO_GLASS (NAME) where DELETE_TS is null ;
create index IDX_RICARDUINO_GLASS_ON_PICTURE on RICARDUINO_GLASS (PICTURE_ID);
