create unique index IDX_RICARDUINO_ACTUATOR_UK_GPIO on RICARDUINO_ACTUATOR (GPIO) where DELETE_TS is null ;
create unique index IDX_RICARDUINO_ACTUATOR_UK_NAME on RICARDUINO_ACTUATOR (NAME) where DELETE_TS is null ;
