alter table RICARDUINO_COCKTAIL add constraint FK_RICARDUINO_COCKTAIL_ON_GLASS foreign key (GLASS_ID) references RICARDUINO_GLASS(ID);
alter table RICARDUINO_COCKTAIL add constraint FK_RICARDUINO_COCKTAIL_ON_PICTURE foreign key (PICTURE_ID) references SYS_FILE(ID);
create unique index IDX_RICARDUINO_COCKTAIL_UK_NAME on RICARDUINO_COCKTAIL (NAME) where DELETE_TS is null ;
create index IDX_RICARDUINO_COCKTAIL_ON_GLASS on RICARDUINO_COCKTAIL (GLASS_ID);
create index IDX_RICARDUINO_COCKTAIL_ON_PICTURE on RICARDUINO_COCKTAIL (PICTURE_ID);
