alter table RICARDUINO_COCKTAIL add constraint FK_RICARDUINO_COCKTAIL_ON_PICTURE foreign key (PICTURE_ID) references SYS_FILE(ID);
create unique index IDX_RICARDUINO_COCKTAIL_UNIQ_NAME on RICARDUINO_COCKTAIL (NAME) ;
create index IDX_RICARDUINO_COCKTAIL_ON_PICTURE on RICARDUINO_COCKTAIL (PICTURE_ID);
