alter table RICARDUINO_COCKTAIL add constraint FK_RICARDUINO_COCKTAIL_ON_GLASS foreign key (GLASS_ID) references RICARDUINO_GLASS(ID);
create index IDX_RICARDUINO_COCKTAIL_ON_GLASS on RICARDUINO_COCKTAIL (GLASS_ID);
