alter table RICARDUINO_INGREDIENT add constraint FK_RICARDUINO_INGREDIENT_ON_ACTUATOR foreign key (ACTUATOR_ID) references RICARDUINO_ACTUATOR(ID);
create index IDX_RICARDUINO_INGREDIENT_ON_ACTUATOR on RICARDUINO_INGREDIENT (ACTUATOR_ID);
